error-invalid-openplatform    : The resource doesn't contain any information about OpenPlatform.
error-invalid-userid          : Invalid user id.
error-permission              : You don't have permission for this operation.
error-login                   : You typed a bad credentials.
error-login-ddos              : Your computer has been blocked for 15 minutes.
error-login-useragent         : Your web browser is not supported.
error-login-blocked           : Your account has been blocked. Please contact administrator.
